### ISSUE TITLE
Need help with output parameter - SQL Server 2016

### ISSUE THREAD

**Issue by Snackin** [livehelpnow/tds#121]
Hello, any help appreciated. Searching the Internet isn't giving me what I need and I apologize for opening an issue, but Obi Wan Kenobi, you're my only hope :)

Error is:
mssql: %{
     class: 16,
     line_number: 0,
     msg_text: "The formal parameter \"@MeValid\" was not declared as an OUTPUT parameter, but the actual parameter passed in requested output.",
     number: 8162,
     proc_name: "",
     server_name: "HDSQLAPP16",
     state: 2
   }

I've tried various permutations of the following code (notice I have three SQL statements I've been playing with):

```
parameters = [
            %Tds.Parameter{name: "@CollectionId", value: collection_id},
            %Tds.Parameter{name: "@BlaggoOne", direction: :output},
            %Tds.Parameter{name: "@MeValid", direction: :output} # bit Value
        ]

        # sql = "dbo.usp_IsCollectionHierarchyValid_Recursive @CollectionId, @CollectionIdList, @IsValid"
        sql = "dbo.usp_IsCollectionHierarchyValid_Recursive @CollectionId, @CollectionIdList = @BlaggoOne output, @IsValid = @MeValid output"
        # sql = "exec dbo.usp_IsCollectionHierarchyValid_Recursive @CollectionId, @CollectionIdList = @CollectionIdInChain output, @IsValid = @IsValid output"
        :poolboy.transaction(:DBPool, fn pid -> Tds.query_multi(pid, sql, parameters) end, 5000)
```

The Stored Procedure works fine if called from SSMS, but I cannot seem to find the right syntax to call the Stored Procedure from Elixir (No Ecto - using TDS straight)

Does TDS Support Using the Output Parameters in this way? If so, where am I going wrong in the syntax?

Thanks for any help you can provide.

-Snackin

P.S. - I have tons of Stored Procedures in the code, all of them work just fine through TDS. It's just the Output Parameter thing I'm having trouble with. Pooling and everything is working great otherwise!

**Comment by mjaric** [comment]
It is not supported since Tds.Result lack attribute for it.

Funny fact is that output parameters are decoded internally but not returned after (e.g. @handle parameter for rpc calls)

**Comment by Snackin** [comment]
Perfect! Thanks for the reply. I'll modify the Recursive Procedure to pass back a recursion level number. Then, use query_multi to get the result list and go find the one at recursion level 0 - viola! Results. I appreciate the reply!
