### ISSUE TITLE
A few db_connection callbacks are only returning state

### ISSUE THREAD

**Issue by graves** [livehelpnow/tds#26]
There are some db_connection callbacks in lib/tds/protocol.ex I’m unsure of how to handle: checkin, checkout, and ping. Right now they are not doing anything besides returning the original state. 

Any input or pull requests are greatly appreciated.

**Comment by graves** [comment]
https://github.com/livehelpnow/tds/commit/e97983e988fee940a74b7803dd184ac55a34c4dc takes care of checkin and checkout.

I have yet to find a PING or equivalent message in the TDS protocol docs.

**Comment by mjaric** [comment]
I added changed PING callback as `SELECT "pong"` query since we need some way to check if connection is dead.
