### ISSUE TITLE
Sending Float with more than 9 characters fails to insert data

### ISSUE THREAD

**Issue by misaelpc** [livehelpnow/tds#33]
`Tds.Connection.query(pid, "INSERT INTO hades_sealed_cfdis ([total] ,[inserted_at], [updated_at]) VALUES (@1,@2,@3)", [%Tds.Parameter{name: "@1", value: 762213236.1},%Tds.Parameter{name: "@2", value: {{2016, 12, 20}, {23, 59, 23, 0}}},%Tds.Parameter{name: "@3", value: {{2016, 12, 20}, {23, 59, 23, 0}}}])`

`{:error,
 %Tds.Error{message: nil,
  mssql: %{class: 16, length: 404, line_number: 1,
    msg_text: "The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 3 (\"@.1.\"): Data type 0x6D has an invalid data length or metadata length.",
    number: 8016, proc_name: "", server_name: "WIN-96BL2N05ERO", state: 46}}}`

**Comment by mjaric** [comment]
fixed in tds 1.0.4
