### ISSUE TITLE
Project status and Erlang ODBC alternative

### ISSUE THREAD

**Issue by vais** [livehelpnow/tds#34]
Just curious if Elixir tds driver is still a thing, and whether there will be Ecto 2 support any time soon (if ever). Not to prod, just an honest question if anyone's still interested in working on this.

A separate but related question, what prompted you to write a native tds driver versus going with a wrapper for Erlang's own ODBC application? Are there issues (stability? performance?) with [Erlang's ODBC application](http://erlang.org/doc/man/odbc.html)? (Also [a nice writeup here](http://dataidol.com/tonyrogerson/2013/04/17/erlang-running-concurrent-queries-against-microsoft-sql-server/) - it even shows using Windows authentication in the connection string!)

The rationale for moving forward with native tds route instead of using ODBC would also make a great addition to the readme...

**Comment by danielicardopcnt** [comment]
I'm trying to revive this just in case anyone still needs the adapter

**Comment by vais** [comment]
@danielicardopcnt great news, and good luck! In the meantime, I'm gonna go ahead and close this issue. 

P.S. Regarding ODBC as an alternative, the main reasons to not use that, as far as I understand, are:
1. Windows only
2. Performance
3. Considered to be a legacy technology by MS

**Comment by cristianberneanu** [comment]
For anyone else interested in this, I would like to add that the ODBC implementation in Erlang is very buggy / unstable / old when it comes to SQL Server. Types like `(n)varchar(max)`, `uniqueidentifier` and `blob` aren't supported (or even worse, crash the VM).
