### ISSUE TITLE
Getting CaseClauseError in Tds.Protocol.ping

### ISSUE THREAD

**Issue by kevinsheffield** [livehelpnow/tds#40]
Firing up a new phoenix app and receiving the following every few seconds in the console.

> [error] GenServer #PID<0.318.0> terminating
** (CaseClauseError) no case clause matching: {:ok, %Tds.Result{columns: ["msg"], command: nil, num_rows: 1, rows: [["pong"]]}, %Tds.Protocol{env: %{trans: <<0>>}, itcp: nil, opts: [password: :REDACTED, idle_timeout: 5000, name: Home.Repo.Pool, otp_app: :home, repo: Home.Repo, timeout: 15000, pool_timeout: 5000, adapter: Tds.Ecto, database: "redacted", username: "redacted", hostname: "redacted", pool_size: 10, pool: DBConnection.Poolboy], pak_data: "", pak_header: "", query: nil, result: %Tds.Result{columns: ["msg"], command: nil, num_rows: 1, rows: [["pong"]]}, sock: {:gen_tcp, #Port<0.8983>}, state: :ready, tail: "", transaction: nil, usock: nil}}
    (tds) lib/tds/protocol.ex:62: Tds.Protocol.ping/1
    (db_connection) lib/db_connection/connection.ex:358: DBConnection.Connection.handle_info/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout
State: {Tds.Protocol, %Tds.Protocol{env: %{trans: <<0>>}, itcp: nil, opts: [password: :REDACTED, idle_timeout: 5000, name: Home.Repo.Pool, otp_app: :home, repo: Home.Repo, timeout: 15000, pool_timeout: 5000, adapter: Tds.Ecto, database: "redacted", username: "redacted", hostname: "redacted", pool_size: 10, pool: DBConnection.Poolboy], pak_data: "", pak_header: "", query: nil, result: %Tds.Result{columns: nil, command: nil, num_rows: 0, rows: []}, sock: {:gen_tcp, #Port<0.8983>}, state: :executing, tail: "", transaction: nil, usock: nil}}

**Comment by woylie** [comment]
The fix is merged, but the Hex release 1.0.4 was apparently built from the latest Github tag 1.0.2, which doesn't include the fix. Can someone please make a proper release?

**Comment by mjaric** [comment]
1.0.5 is released in hex now. It should include pr #41
