### ISSUE TITLE
Missing DBConnection callbacks for cursors

### ISSUE THREAD

**Issue by woylie** [livehelpnow/tds#43]
There are some warnings about undefined behaviour functions related to cursors: `handle_deallocate/4`, `handle_declare/4`, `handle_first/4` and `handle_next/4`.

[Callback definitions](https://github.com/elixir-ecto/db_connection/blob/0e2dd70939b7e8da8e59af982c0a3c557bfca37e/lib/db_connection.ex#L268)

[T-SQL documentation](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/cursors-transact-sql)

**Comment by mjaric** [comment]
If you are not using cursors in sql statements you should be fine. This is not yet implemented in tds adapter

**Comment by woylie** [comment]
I know, I would just like to keep track of things to do here, in case someone wants to contribute.

By the way, it would be very helpful if the changelog was kept up to date when a new version is being released.
