### ISSUE TITLE
Tds.Result struct: command?

### ISSUE THREAD

**Issue by woylie** [livehelpnow/tds#47]
The struct definition of `Tds.Result` includes the field `:command`, which is missing from the type and the moduledoc and which doesn't seem to be used anywhere in the library (if I haven't overlooked it somewhere). Can I safely remove it from the struct definition?

**Comment by mjaric** [comment]
I think so, because that and Tds.Utils.error/2 and Tds.Utils.reply are leftovers from v0.X since they were used reply on queued commands.

**Comment by woylie** [comment]
Good, I deleted it in PR #46.

**Comment by mjaric** [comment]
released in v1.0.8
