### ISSUE TITLE
unused expression in decode_decimal

### ISSUE THREAD

**Issue by swsch** [livehelpnow/tds#5]
I went through the code tagging unused variables and came upon this:

lib/tds/types.ex raises a warning during compilation:

```lib/tds/types.ex:549: warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)```

Should that be `value = case sign do...`? I have neither tried it nor checked the tests, but it would make sense to me.

**Comment by mobileoverlord** [comment]
You were right, good catch. Fixed in master
