### ISSUE TITLE
How to call stored procedure?

### ISSUE THREAD

**Issue by dmarko484** [livehelpnow/tds#56]
I'm currently testing tds library but have some initial problems. My communication with MSSQL is primarly based on calling stored procedures. I did connection setup properly and now when calling SP with name 'sp_P3DodavExpo' I'm getting no results

```
iex(22)> Tds.query(dbPid, "sp_P3DodavExpo", [])                                      
{:ok, %Tds.Result{columns: nil, num_rows: 0, rows: []}}
```
When I misspel procedure name in Tds.query calling I'm getting a correct error message from server so connection is working fine. But dont udesrtand why cant see any rows in result set. Is this a proper stored procedure calling syntax?

**Comment by mjaric** [comment]
It should work if stored procedure has `SET NOCOUNT ON;` and if it returns single result set, otherwise it will give you some strange results.

**Comment by dmarko484** [comment]
Procedure return a  list of items = rows, each row contains several columns. It doesn't work with such data? our former system is based on JAVA and its TDS driver implementation, its working with no problem  here.

**Comment by mjaric** [comment]
what I meant is this

```sql
-- this will NOT work since it returns multiple result sets and does not set NOCOUNT to ON
create procedure dbo.multy_result_set_doenst_work
as

	select id, name, email
	from dbo.users

	select id, address_line1, address_line2, pobox, city, user_id
	from dbo.user_addresses 
go



-- this will work since it returns single result set and sets NOCOUNT to ON
create procedure dbo.single_result_set_works
as
	SET NOCOUNT ON;

	select u.id, u.name, u.email, a.id as address_id, a.address_line1, a.address_line2, a.pobox, a.ciity
	from dbo.users as u
		inner join dbo.user_addresses as a on u.id = a.user_id

go
```

column data types should work for most of the types, except if you have user defined tables or you are trying to use XML columns without casing them to nvarchar

**Comment by dmarko484** [comment]
Thanks a lot!

**Comment by mjaric** [comment]
@dmarko484 could you please confirm that above is your case or it is really some bug in tds implementation? I will gladly try to fix it if you can provide me some details about your case.

Thanks!

**Comment by dmarko484** [comment]
Well, its legacy system provided by customer so we can't update the procedures. Customer runs this as a counterpart to our existing web app. Not sure they will agree on such change as current java driver works fine with these procedures. (they provide up to 60 procedures for our app)

**Comment by dmarko484** [comment]
Ok, just tested with a few other stored procedures and its working fine ... thanks!
