### ISSUE TITLE
pins missing in rpc_test.exs?

### ISSUE THREAD

**Issue by swsch** [livehelpnow/tds#6]
```
$ mix test
...
test/rpc_test.exs:32: warning: variable num is unused
test/rpc_test.exs:43: warning: variable num is unused
test/rpc_test.exs:54: warning: variable num is unused
test/rpc_test.exs:65: warning: variable str is unused
test/rpc_test.exs:76: warning: variable str is unused
```
After checking the [docs](http://elixir-lang.org/getting-started/pattern-matching.html#the-pin-operator), I am wondering if the asserts there should not be using `^num` and `^str` on the left hand side.

**Comment by mobileoverlord** [comment]
I was able to silence the warning by pinning the strings, unfortunately pinning Decimal just interpolates its representation and fails check. Not sure what to do about those.

**Comment by mobileoverlord** [comment]
I broke these out and used Decimal. Fixed in master
