### ISSUE TITLE
MatchError upon Connecting

### ISSUE THREAD

**Issue by HangingClowns** [livehelpnow/tds#68]
Using Tds 1.1.2 on Windows 10 using SQL Express

I keep getting this error when trying to connect. It looks like it's blowing up when trying to receive data back from the UDP connection on 204. I ran each of these, line by line, and I was able to reproduce this error.

```
** (RuntimeError) Connect raised a MatchError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (tds) lib/tds/protocol.ex:204: Tds.Protocol.instance/2
    (tds) lib/tds/protocol.ex:56: Tds.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Tds.Protocol
```

**Comment by mjaric** [comment]
I will check this as soon as I prepare virtual machine with Windows and sql server installed as instance. In mean time, if possible just enable TCP connection on some port in SQL Server Configuration Manager so you can connect without specifying instance name.

Thank you for reporting this issue.

**Comment by HangingClowns** [comment]
It seems that this may be related to the user account not having permission to that database. Maybe it would be better to give a better error?

**Comment by HangingClowns** [comment]
was my last comment implemented?
