### ISSUE TITLE
Unexpected Environment Change message kills the connection

### ISSUE THREAD

**Issue by marpo60** [livehelpnow/tds#72]
Hi,

Thanks for this great library!

While connecting to one SQL server, the connection was being killed right after connecting. I dig into the actual message that the client was receiving and I found out that, in my case I was receving shortly after a successful login a Environment Change message with the code 13.

After reading [this](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-TDS/[MS-TDS].pdf) I found out that the code belong to "Real Time Log Shipping/Database Mirroring
Partner" messages.

In the meanwhile I adjusted the function that decodes this kind of message https://github.com/livehelpnow/tds/blob/00a899f47d2649c33c5b08980c86837b8617913e/lib/tds/tokens.ex#L218 and added the "13" case as a no-op.

If you think is useful I can open a PR.

**Comment by mjaric** [comment]
Hi,

PR is always welcome. Anyhow I don't have environment where to test this feature

**Comment by mjaric** [comment]
released in v1.1.5
