### ISSUE TITLE
Ecto 3 support

### ISSUE THREAD

**Issue by collegeimprovements** [livehelpnow/tds#75]
Thanks for creating this package. 
Is Ecto-3 supported? 
We are getting compile time error when we mention `adapter: Tds.Ecto` in Ecto-3 Repo.

**Comment by mjaric** [comment]
As mentioned [here](https://github.com/livehelpnow/tds_ecto/issues/69) we are working on migration to ecto_sql repo, once done 3.x will be supported.

BTW since tds v2.0 ecto 2.x is supported trough support-1.1 branch  for any security or bug fixes
