### ISSUE TITLE
Exception processing small tail

### ISSUE THREAD

**Issue by jfis** [livehelpnow/tds#8]
Sometimes what is left over after completing a packet is not long enough to be the packet header for the next packet, leading to seemingly random errors. The same query may even succeed the next time.

The larger the return data the more likely this bug could slip in.  

Example exception looks like:

    Tds.Connection.query(pid, "SELECT TOP(1000) * FROM [Clients] ORDER BY [ClientId] ASC", [])
    ** (EXIT from #PID<0.110.0>) an exception was raised:
      ** (MatchError) no match of right hand side value: <<4, 0, 16, 0, 0, 52>>
        (tds) lib/tds/connection.ex:286: Tds.Connection.new_data/2
        (tds) lib/tds/connection.ex:229: Tds.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

**Comment by jfis** [comment]
PR #9

**Comment by mobileoverlord** [comment]
Merged
