### ISSUE TITLE
Confusion with README for ecto_sql support.

### ISSUE THREAD

**Issue by LoganBresnahan** [livehelpnow/tds#81]
The README states: "Since TDS version 2.0, tds_ecto package is deprecated, this version supports ecto_sql since version 3.1.0.", but there is no adapter option listed that replaces tds_ecto.
https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#module-built-in-adapters

**Comment by mjaric** [comment]
[ecto_sql fork](https://github.com/mjaric/ecto_sql) is not complete yet. And if you try to override tds version in app that uses latest tds_ecto it will not work since DbConnection 2.0 is required for tds 2.0.

In other words, don't use tds 2.0, it is work in progress

**Comment by LoganBresnahan** [comment]
Thanks for your work on this project and for clearing that up. I'm going to go ahead and close this issue now.

**Comment by mjaric** [comment]
You are welcome
