### ISSUE TITLE
uniqueidentifier columns return incorrect binary

### ISSUE THREAD

**Issue by ericlathrop** [livehelpnow/tds#84]
If I select a uniqueidentifier column, the binary I get back isn't in the correct format.
Here's a database query using `mssql-cli`:
```
> select top 1 UserId from dbo."aspnet_Users" where UserName = 'elathrop';
+--------------------------------------+
| UserId                               |
|--------------------------------------|
| 1557b0fd-40ad-4c6e-9651-161136ad68d2 |
+--------------------------------------+
```
Here's what I get using `tds`:
```
iex(46)> Tds.query!(pid, "select top 1 UserId from dbo.\"aspnet_Users\" where UserName = 'elathrop'", [])
%Tds.Result{
  columns: ["UserId"],
  num_rows: 1,
  rows: [
    [<<253, 176, 87, 21, 173, 64, 110, 76, 150, 81, 22, 17, 54, 173, 104, 210>>]
  ]
}
iex(47)> UUID.binary_to_string!(<<253, 176, 87, 21, 173, 64, 110, 76, 150, 81, 22, 17, 54, 173, 104, 210>>)
"fdb05715-ad40-6e4c-9651-161136ad68d2"
```

Here's what the binary should look like:
```
iex(50)> UUID.string_to_binary!("1557b0fd-40ad-4c6e-9651-161136ad68d2")
<<21, 87, 176, 253, 64, 173, 76, 110, 150, 81, 22, 17, 54, 173, 104, 210>>
```
Notice that the second half is correct, but the first half has all the same bytes, just in the wrong order.

**Comment by mjaric** [comment]
that is because MS always has it own standards, use `Tds.UUID.load/1` to get string representation, also, when you want to put binary into sql table, use `Tds.UUID.dump/1` before you create parameter for query

**Comment by mjaric** [comment]
One more thing, don't use other elixir UUID libs since they do not produce valid binary, instead use Tds.UUID.generate

**Comment by ericlathrop** [comment]
That would be useful information in the documentation.

**Comment by mjaric** [comment]
https://github.com/livehelpnow/tds/blob/master/CHANGELOG.md
