### ISSUE TITLE
Example of how to use with `ecto_sql`?

### ISSUE THREAD

**Issue by ericlathrop** [livehelpnow/tds#90]
The README says this library is compatible with `ecto_sql` from 3.1.0 on, but it doesn't describe how to use it. I found [the fork where the Ecto adapter is being created](https://github.com/mjaric/ecto_sql/tree/tds-support), but it doesn't look like it's been merged into mainline `ecto_sql` yet.

Am I missing something? Is the README correct? Is there some way to use this with Ecto 3.x? Is there some way I can help?

**Comment by mjaric** [comment]
Hi @ericlathrop, plan was to finish it and merge with 3.1.0, but due busyness with other stuff it stalled. Tds `master` branch is using DbConnection 2.0 so it should be ready for 3.X usage but need complete ecto adapter. I will probably continue working on sql_ecto fork at October.

**Comment by mjaric** [comment]
Hi Eric, that is awesome! thanks! I will try to create series of issues in repo so it can be easily tracked.

**Comment by vais** [comment]
@mjaric @ericlathrop super excited about this development, thank you!

**Comment by WernerBuchert** [comment]
Hi, are there any news about this?

**Comment by mjaric** [comment]
I'm fully focused now on this and should be out in next few weeks in v3.3 I think
