### ISSUE TITLE
Where to find list of config options?

### ISSUE THREAD

**Issue by bisade** [livehelpnow/tds#91]
The README includes an example configuration section which shows some of the available config options. It will be nice to have a section showing all available config options and possible values where applicable.

I am executing a long running query for an ETL pipeline but i get `08:26:45.253 [error] Tds.Protocol (#PID<0.453.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.407.0> timed out because it queued and checked out the connection for longer than 15000ms
{:error,
 %DBConnection.ConnectionError{
   message: "connection is closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)"
 }}`

I would like to know how to increase the timeout

**Comment by vais** [comment]
@bisade you can pass the desired `:timeout` in milliseconds as an option to `Tds.query` and friends.

Here's a failing case:
```
iex(10)> Tds.query!(pid, "WAITFOR DELAY '00:00:20'", [])                 
10:05:39.077 [error] Tds.Protocol (#PID<0.311.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.433.0> timed out because it queued and checked out the connection for longer than 15000ms
```
Now, same SQL with `:timeout` set to 30 seconds:
```
iex(10)> Tds.query!(pid, "WAITFOR DELAY '00:00:20'", [], timeout: 30_000)
%Tds.Result{columns: nil, num_rows: 0, rows: []}
```

Hope this helps!

**Comment by bisade** [comment]
@vais thanks. 

It was quite helpful.
